import { Booking } from './types/UI';

export const bookings: Booking[] = [
  {
    id: '1',
    serviceImage: 'https://example.com/images/laundry1.jpg',
    charge: 4500,
    service: 'laundry',
    status: 'completed',
    description: 'Washed and ironed 10 shirts and trousers.',
    date: '2025-10-15',
    address: '12, Ogundele Street, Lagos',
    provider: {
      id: 'p1',
      name: 'CleanPro Laundry',
      userAvatar: 'https://example.com/avatars/laundry.png',
      location: 'Ikeja, Lagos',
      rating: 4.7,
      rateAmount: 122,
      price: 4500,
      service: 'laundry',
    },
  },
  {
    id: '2',
    serviceImage: 'https://example.com/images/cleaning1.jpg',
    charge: 8000,
    service: 'cleaning',
    status: 'pending',
    description: 'Deep cleaning for a 3-bedroom apartment.',
    date: '2025-10-20',
    address: '45, Adeola Street, Yaba',
    provider: {
      id: 'p2',
      name: 'SparkleClean Services',
      userAvatar: 'https://example.com/avatars/cleaning.png',
      location: 'Yaba, Lagos',
      rating: 4.9,
      rateAmount: 240,
      price: 8000,
      service: 'cleaning',
    },
  },
  {
    id: '3',
    serviceImage: 'https://example.com/images/plumbing1.jpg',
    charge: 6500,
    service: 'plumbing',
    status: 'pending',
    description: 'Fixed kitchen sink leakage and replaced pipe.',
    date: '2025-10-22',
    address: '18, Allen Avenue, Ikeja',
    provider: {
      id: 'p3',
      name: 'AquaFlow Plumbing',
      userAvatar: 'https://example.com/avatars/plumber.png',
      location: 'Ikeja, Lagos',
      rating: 4.6,
      rateAmount: 175,
      price: 6500,
      service: 'plumbing',
    },
  },
  {
    id: '4',
    serviceImage: 'https://example.com/images/carpentry1.jpg',
    charge: 12000,
    service: 'carpentry',
    status: 'completed',
    description: 'Built a custom wooden shelf and repaired door frame.',
    date: '2025-10-10',
    address: '22, Bode Thomas, Surulere',
    provider: {
      id: 'p4',
      name: 'WoodMaster Carpentry',
      userAvatar: 'https://example.com/avatars/carpentry.png',
      location: 'Surulere, Lagos',
      rating: 4.8,
      rateAmount: 199,
      price: 12000,
      service: 'carpentry',
    },
  },
  {
    id: '5',
    serviceImage: 'https://example.com/images/electrical1.jpg',
    charge: 5500,
    service: 'electrical',
    status: 'pending',
    description: 'Installed new ceiling fan and repaired socket.',
    date: '2025-10-25',
    address: '5, Toyin Street, Ikeja',
    provider: {
      id: 'p5',
      name: 'PowerFix Electricals',
      userAvatar: 'https://example.com/avatars/electrician.png',
      location: 'Ikeja, Lagos',
      rating: 4.5,
      rateAmount: 150,
      price: 5500,
      service: 'electrical',
    },
  },
  {
    id: '6',
    serviceImage: 'https://example.com/images/painting1.jpg',
    charge: 15000,
    service: 'painting',
    status: 'completed',
    description: 'Painted living room and two bedrooms with premium finish.',
    date: '2025-09-28',
    address: '8, Herbert Macaulay Way, Yaba',
    provider: {
      id: 'p6',
      name: 'ColorCrest Painters',
      userAvatar: 'https://example.com/avatars/painter.png',
      location: 'Yaba, Lagos',
      rating: 4.9,
      rateAmount: 302,
      price: 15000,
      service: 'painting',
    },
  },
  {
    id: '7',
    serviceImage: 'https://example.com/images/barbing1.jpg',
    charge: 3000,
    service: 'barbing',
    status: 'completed',
    description: 'Premium haircut and beard trim at home service.',
    date: '2025-10-26',
    address: '3, Adetokunbo Ademola, Victoria Island',
    provider: {
      id: 'p7',
      name: 'SharpCuts Mobile Barbers',
      userAvatar: 'https://example.com/avatars/barber.png',
      location: 'Victoria Island, Lagos',
      rating: 4.8,
      rateAmount: 410,
      price: 3000,
      service: 'barbing',
    },
  },
  {
    id: '8',
    serviceImage: 'https://example.com/images/cleaning2.jpg',
    charge: 10000,
    service: 'cleaning',
    status: 'cancelled',
    description: 'Office space cleaning for 5 rooms.',
    date: '2025-10-27',
    address: '32, Awolowo Road, Ikoyi',
    provider: {
      id: 'p8',
      name: 'CrystalClean Professionals',
      userAvatar: 'https://example.com/avatars/cleaning2.png',
      location: 'Ikoyi, Lagos',
      rating: 4.7,
      rateAmount: 280,
      price: 10000,
      service: 'cleaning',
    },
  },
  {
    id: '9',
    serviceImage: 'https://example.com/images/plumbing2.jpg',
    charge: 7000,
    service: 'plumbing',
    status: 'completed',
    description: 'Replaced faulty bathroom tap and unclogged drain.',
    date: '2025-10-18',
    address: '14, Ogba Road, Lagos',
    provider: {
      id: 'p9',
      name: 'PipeFix Experts',
      userAvatar: 'https://example.com/avatars/plumber2.png',
      location: 'Ogba, Lagos',
      rating: 4.5,
      rateAmount: 120,
      price: 7000,
      service: 'plumbing',
    },
  },
  {
    id: '10',
    serviceImage: 'https://example.com/images/laundry2.jpg',
    charge: 4000,
    service: 'laundry',
    status: 'cancelled',
    description: 'Pickup and wash of bed sheets and curtains.',
    date: '2025-10-12',
    address: '21, Akerele Street, Surulere',
    provider: {
      id: 'p10',
      name: 'Swift Laundry Hub',
      userAvatar: 'https://example.com/avatars/laundry2.png',
      location: 'Surulere, Lagos',
      rating: 4.3,
      rateAmount: 88,
      price: 4000,
      service: 'laundry',
    },
  },
];
